sudo: false
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libsdl2-dev
      env:
        - CC="clang-5.0"
        - CXX="clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libsdl2-dev
      env:
        - CC="gcc-7"
        - CXX="g++-7"
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then export DISPLAY=:99.0;         fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sleep 3;                      fi
script:
  - "ruby run_test.rb -v all test"
