sudo: false
matrix:
  include:
    - os: linux
    - os: osx
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install sdl2; fi
script:
  - "ruby run_test.rb all test"
addons:
  apt:
    packages:
      - libsdl2-dev
