sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode9.2
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install sdl2; fi
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then export DISPLAY=:99.0;         fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sleep 3;                      fi
script:
  - "ruby run_test.rb all test"
addons:
  apt:
    packages:
      - libsdl2-dev
